### ISSUE TITLE
Docker Container Exits

### ISSUE THREAD

**Issue by bmcgowan32** [sktaylortrash/TCPLightingWebInterface-MQTT-Docker#3]
Im hoping for a bit of guidance.  I cloned your repo, adjusted the docker-compose to reflect my bridge IP and MQTT info, but the container wont stay running.  Ive tried it on a Ubuntu machine running docker engine, and on both OSX and Windows running Docker Desktop.  All of my environments run other containers successfully, but none can start this one.

Every time it stops the container just after calling the subscriber.  I can talk to the httpd during the startup, so I am pretty sure my port mappings and such are good.  It kinda looks as if the boot.sh scripts aren't executing properly, as I dont see the updates to the config.inc.php either?

**Comment by sktaylortrash** [comment]
First off thanks for trying this out.  I never know if I'm the only one using it or not.

A couple of things off the top of my head where I've observed this behaviour.

The credentials file tcp.token is critical to the app's function. 
- It sometimes needs to be manually created as a blank file on your storage outside the container in advance. This seems to vary from operating system to operating system.
- Also, make sure the path to tcp.token under volumes is correct.  I have mine in a subfolder of where docker-compose.yml is located called tcplights so my path is  './tcplights/tcp.token:/var/www/html/tcp.token'

Occasionally when testing some of my bridges needed to be in pairing mode before starting the container.  I have 5 bridges all on the same firmware version and 2 require this from time to time. I could not find a reproducible pattern

**Comment by bmcgowan32** [comment]
Thanks!  And "Thank You!" for this tool. Ive been running the MQTT version for a year or so and it made my life so much easier!  Ill give these ideas a try!

**Comment by bmcgowan32** [comment]
So here's a bit more info.  When I inspect the container after the run, I can see that the layers from the Dockerfile are being executed.  Things like the apache config changes, the insertion of the /var/www/html dir, etc all seem to go fine.  But then when it calls boot.sh, its like the ENV variables set in docker-compose arent making it.  The sed changes dont appear to get applied.  Then it does successfully startup apache and run the curls to get the MQTT stuff.  But I am guessing that since its not getting the variables, it isnt going to the right IP/URL, and as such the mqtt_sub.py file is empty.  And when it tried to run that, the container just dumps.  Im going to go back and see if there is any debugging for the env variable that I can set.  I think thats my issue...

**Comment by sktaylortrash** [comment]
That is strange I haven't run across the sed stuff not working before.  But until now I didn't know if I was the only user of this version.  

If you want to post your compose I can sanity-check that something isn't amiss there for you.

**Comment by bmcgowan32** [comment]
Thank you! I might take you up on the offer.  I figured out the biggest issue... I was using "docker run" vs "docker compose" to spin up the container.  Rookie move.

However, I still have a missing substitution from the ENV, and I am still crashing out when calling mqtt_sub.py.  I think I found the missing substituion Ive been trying to debug the ENV passing overall.  It looks like the variable names for the pub/sub topics dont quite line up.  In the docker-compose file they have an upper case character, but in the boot.sh (sed commands), they are lower case:

In docker-compose:

- **MQTT_subscriber**=tcp-subscriber           # Only needs to be changed if you are running multiple bridge instances
- **MQTT_publisher**=tcp-publisher             # Only needs to be changed if you are running multiple bridge instances

in boot.sh:

sed -i "s|MQTTSubscriber|$**MQTT_Subscriber**|" /var/www/html/config.inc.php
sed -i "s|MQTTPublisher|$**MQTT_Publisher**|" /var/www/html/config.inc.php

So the sed substitution leaves thse values empty in the config.inc.php.  Not sure if that is what is ultimately what crashing the mqtt_sub.py, but I am further along!!

**Comment by bmcgowan32** [comment]
Upon more playing, adjusting the docker-compose file variable names to match boot.sh fixed the substitution  problem.  I just had to dump the container and start from a fresh config.  So now I just need to figure out why mqtt_sub.py is failing.  I've tried it both with a DNS name and IP..  Verified that the container is able to resolve the DNS name and that it has connectivity to the MQTT port on my HA box.

Still digging...

2023-09-08 10:52:56 /var/www/html/mqtt_sub.py: line 1: syntax error near unexpected token `'homeassistant.local','
2023-09-08 10:52:56 /var/www/html/mqtt_sub.py: line 1: `client.connect('homeassistant.local', 1883,60)'

**Comment by sktaylortrash** [comment]
Ah, good catch on the case. Had both lowercase on my local but never pushed that to Git Hub. Will push now.  

I've never used Home Assistant's internal MQTT server I always spin up my own in another container. So I can reboot HA without taking down everything else.

It also lets me make this container dependent on my MQTT container being running and healthy before attempting to start.

    depends_on: \
      mosquitto: \
        condition: service_healthy

**Comment by bmcgowan32** [comment]
Thanks for the update to the repo...  One more tiny change though, should be "MQTT_publisher" not "MQTT_sublisher"

sed -i "s|MQTTPublisher|$**MQTT_sublisher**|" /var/www/html/config.inc.php

**Comment by sktaylortrash** [comment]
Lol fixed

**Comment by bmcgowan32** [comment]
Oh!  This is a really good idea for deploying the mqtt broker!  I'm going to try that out next!

**Comment by sktaylortrash** [comment]
I just pushed an alternate docker-compose that has the Broker and dependencies configured

**Comment by sktaylortrash** [comment]
I've also just pushed a corrected version to docker hub as I forgot to do that as well

**Comment by bmcgowan32** [comment]
Thank you for all the help!  I have the container running successfully!  Tips for future users:

Setup a BLANK token file before you compose the container.  I tried copying in my tcp.token file from another running instance and it didn't work.  Just start with a empty file and grab a new token at boot.  I tried starting without a token file and letting the setup script create one...that also didn't work.  Best practice would be to follow the instructions above:
- clone the repo
- modify docker-compose to set your bridge IP/port and your MQTT broker ip/port/username/password
- create a directory inside the cloned repo named "tcplights"
- touch a blank file in the tcplights directory named "tcp.token"
- Put your bridge in pairing mode before you run "docker compose up"
- If you have trouble, be sure to delete any volumes from previous runs where the token was missing/invalid (find them with "docker ps -a" and remove them with "docker rm -v <volume>") before trying to start the container.  I had weird issues with the token file mount if I didn't remove the old volumes

Thanks @sktaylortrash for all your help!!

**Comment by sktaylortrash** [comment]
Great to hear. 
You honestly shouldn't need to clone the repo. Just use the docker-compose file of your choice.  
The code in the repo would only be necessary if you wanted to build your own version of the image.   Otherwise, the one hosted on docker hub and referenced in the compose file should be the same

**Comment by sktaylortrash** [comment]
@bmcgowan32 thanks again for helping iron out the issues. I've updated the readme with some of your points and also linked to additional info for anyone wanting to the broker dependency stuff.  Should definitely help anyone else who comes along next
