### ISSUE TITLE
Possible Windows Characters in scripts?

### ISSUE THREAD

**Issue by bmcgowan32** [sktaylortrash/TCPLightingWebInterface-MQTT-Docker#4]
Hey!  I had to blow away my previous docker setup and I tried to follow the updated instructions, but I think I found an issue.  For my previous setup, I had cloned the whole github repo and built the container up from source files.  This time I tried to use docker compose to pull the image from the docker HUB.  I also tried doing a docker pull of the image and then running it against my compose file.  Both times, the container fails to boot on my Ubuntu docker host.  Digging into the files, I think the config scripts (boot.sh, etc) have some non-displayable characters in them, likely windows EOL characters.  When I do a docker exec -it <image>  /bin/bash and look at the script files in /tmp, they all have ^M at the end of the line.  This seems to mess with executing during the compose? 

Here's a sample of the file from a freshly pulled image in docker hub:

root@093ccd825a39:/tmp# cat -v boot.sh 
#!/bin/bash^M
^M
# Set up config.inc.php^M
sed -i "s/TCPBRIDGEIP/$TCPBRIDGE_IP/" /var/www/html/config.inc.php^M
sed -i "s/TCPBRIDGEPORT/$TCPBRIDGE_PORT/" /var/www/html/config.inc.php^M
sed -i "s|LOCALURL|$LOCAL_URL|" /var/www/html/config.inc.php^M
sed -i "s|TOKENEMAIL|$TOKEN_EMAIL|" /var/www/html/config.inc.php^M
sed -i "s/TOKENPASSWORD/$TOKEN_PASSWORD/" /var/www/html/config.inc.php^M
sed -i "s/FADEON/$FADE_ON/" /var/www/html/config.inc.php^M
sed -i "s/FADEOFF/$FADE_OFF/" /var/www/html/config.inc.php^M
sed -i "s|TCPTIMEZONE|$TCP_TIMEZONE|" /var/www/html/config.inc.php^M
sed -i "s/TCPLATITUDE/$TCP_LATITUDE/" /var/www/html/config.inc.php^M
sed -i "s/TCPLONGITUDE/$TCP_LONGITUDE/" /var/www/html/config.inc.php^M
sed -i "s/MQTTIP/$MQTT_IP/" /var/www/html/config.inc.php^M
sed -i "s/MQTTPORT/$MQTT_PORT/" /var/www/html/config.inc.php^M
sed -i "s/MQTTUSER/$MQTT_USERNAME/" /var/www/html/config.inc.php^M
sed -i "s/MQTTPASS/$MQTT_PASSWORD/" /var/www/html/config.inc.php^M
sed -i "s|MQTTSubscriber|$MQTT_subscriber|" /var/www/html/config.inc.php^M
sed -i "s|MQTTPublisher|$MQTT_publisher|" /var/www/html/config.inc.php^M
sed -i "s|MQTTPrefix|$MQTT_prefix|" /var/www/html/config.inc.php^M
sed -i "s|MQTTControl|$MQTTcontrol|" /var/www/html/config.inc.php^M
sed -i "s|HADiscovery|$HA_Discovery|" /var/www/html/config.inc.php^M
sed -i "s|HASSTopicID|$HASSTopic_id|" /var/www/html/config.inc.php^M
sed -i "s|HASSOnlineTopic|$HASSOnline|" /var/www/html/config.inc.php^M
^M
#Create Token and logs^M
/var/www/html/setup.sh^M
#Start Apache^M
/usr/sbin/apache2ctl -D FOREGROUND &^M
/tmp/generate_sub.sh &^M
/tmp/run_sub.sh ^M

Any chance you could verify if you're seeing this?  Maybe on a Windows host, this will fly, but on linux its an issue?  If so, could you update the docker hub files to remove the extra EOL characters?

Sorry to make more work.  I really love (and rely on) this project!

**Comment by sktaylortrash** [comment]
Well, that's super weird. I only work on this or any of my other projects in Linux so the presence of CRLF instead of LF makes no sense.  I also only run this in docker on Linux.  
I'm on the road, but I'll see if I can rebuild this on my work computer which is of course windows so it may take me a minute to sort out.

**Comment by sktaylortrash** [comment]
Well, I just pulled everything down from GitHub and no Windows EOL characters existed in any files.  But I force-converted them to LF anyway and rebuilt and pushed an image to dockerhub try specifying the version in your compose 1.0.1a instead of latest or 1.0.1 and see if that changes anything

**Comment by bmcgowan32** [comment]
Hey!  Sorry, I didnt get back to you.  Yes, using 1.0.1a worked as expected.   I hope it wasnt just something I did, but a fresh pull of that image fixed it for me!  Thanks so much!

**Comment by sktaylortrash** [comment]
Great thanks for the update
